### ISSUE TITLE
About license other than creative commons

### ISSUE THREAD

**Issue by stkw0** [sindresorhus/awesome#1206]
Why other licenses a part from creative commons are not acceptable? 
WTFPL for example is not only a code license, it simply says that everybody is free to do whatever they want with it. So, why WTFPL is not an acceptable license for example?

**Comment by sindresorhus** [comment]
> Why other licenses a part from creative commons are not acceptable?

It doesn't say that other licenses are not acceptable, just that code specific licenses are not.

> WTFPL for example is not only a code license, it simply says that everybody is free to do whatever they want with it. So, why WTFPL is not an acceptable license for example?

Because it might offend people and it has absolutely no benefit over the CC licenses. You're of course free to use it if you want, but your list won't be included here. Fostering a welcoming community is important for me, and an unfriendly license is unwelcome.
