### ISSUE TITLE
Browser automation tools

### ISSUE THREAD

**Issue by angrykoala** [sindresorhus/awesome#1404]
Would it make sense an awesome browser automation tools list? I've been looking around and I couldn't find any list regarding this. I'm happy to create one if this list makes sense

**Comment by pcr910303** [comment]
Well, I'm not a contributor or something but I realllllly needed this a few weeks ago :-( I'll be great if there was one ^_^!!


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------발신: Andrés <notifications@github.com> 날짜: 18/9/28  오후 5:58  (GMT+09:00) 받은 사람: sindresorhus/awesome <awesome@noreply.github.com> 참조: Subscribed <subscribed@noreply.github.com> 제목: [sindresorhus/awesome] Browser automation tools (#1404) 
Would it make sense an awesome browser automation tools list? I've been looking around and I couldn't find any list regarding this. I'm happy to create one if this list makes sense

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sindresorhus/awesome","title":"sindresorhus/awesome","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sindresorhus/awesome"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Browser automation tools (#1404)"}],"action":{"name":"View Issue","url":"https://github.com/sindresorhus/awesome/issues/1404"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sindresorhus/awesome/issues/1404",
"url": "https://github.com/sindresorhus/awesome/issues/1404",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Browser automation tools (#1404)",
"sections": [
{
"text": "",
"activityTitle": "**Andrés**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@angrykoala",
"facts": [
{
"name": "Repository: ",
"value": "sindresorhus/awesome"
},
{
"name": "Issue #: ",
"value": 1404
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sindresorhus/awesome\",\n\"issueId\": 1404,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sindresorhus/awesome\",\n\"issueId\": 1404\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sindresorhus/awesome/issues/1404"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385379287\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by angrykoala** [comment]
@pcr910303 Ok, I'll start working on it and see if this gets approved here

**Comment by pcr910303** [comment]
Well, That'll be great! :-) Thanks!

삼성 갤럭시 스마트폰에서 보냈습니다.
null

**Comment by angrykoala** [comment]
Hi @Jogai it is recommended to have a package.json, travis and the lint-tool configured in list?

**Comment by angrykoala** [comment]
Just FYI, I'll be working on this repo: https://github.com/angrykoala/awesome-browser-automation
I'll make a PR when the list is ready

**Comment by pcr910303** [comment]
@angrykoala Great, looking forward for it! I'll try to make a PR(if there's anything not mentioned or better ideas...) once I finish my midterm exams :-)
