### ISSUE TITLE
Awesome list of Responsive Web Design resources

### ISSUE THREAD

**Issue by jyguyomarch** [sindresorhus/awesome#222]
Repo https://github.com/bradfrost/this-is-responsive has an impressive list of resources and patterns for Responsive Web Design.

But it is in the form of a web site (that can be contributed to): http://bradfrost.github.io/this-is-responsive/resources.html

Should it be added as an awesome list?

**Comment by aleksandar-todorovic** [comment]
It makes sense to me to use a website instead of a `.md` file for this purpose.

However, it seems to me like this is one giant list of everything instead of a curated list of awesome things. Seems like pretty much everything submitted gets accepted, and that's not really the point of an awesome list. Plus the list itself is currently unlicensed. There are currently 54 people who contributed to the list, so it would be a really tough job to license it now. Plus it contains no comments on why something is awesome, just linked entries with no description what so ever.

Because of the things I mentioned, I don't think that this list is an `awesome` material.
