### ISSUE TITLE
Add awesome-gamedev

### ISSUE THREAD

**Issue by pizzamaker** [sindresorhus/awesome#340]
https://notabug.org/koz.ross/awesome-gamedev

Awesome-gamedev is much larger than the current one under Game Development.

**Comment by maximveksler** [comment]
+1

**Comment by aleksandar-todorovic** [comment]
When we found out that `awesome-c` list has [switched to notabug.org](https://notabug.org/koz.ross/awesome-c) I basically just [forked it](https://github.com/aleksandar-todorovic/awesome-c) to keep in on GitHub. Back then, @sindresorhus said:

> Lists should be on GitHub as the whole point of them are community collaboration.

[Source](https://github.com/sindresorhus/awesome/issues/167)

I agree with him that this list should keep listing lists on GitHub instead of listing those on other services. As this list targets GitHub users, it seems rather silly to me to include the links from any of the GitHub alternatives. It's not that the alternatives are bad, it's just that creating _another_ user account to submit a pull request complicates the collaboration.

**Comment by arthurvr** [comment]
:-1: We even removed lists before because they weren't maintained on GitHub anymore (https://github.com/sindresorhus/awesome/commit/8236f1a0feda0aa69273f1088234e69b28362a04 for example)
