### ISSUE TITLE
The awesome-c that you have listed here is very far behind mine

### ISSUE THREAD

**Issue by kozross** [sindresorhus/awesome#365]
The awesome-c link you guys have is *severely* behind my mainline, which is not Github-hosted. Unless you have a reason to link to an inferior version purely because it's on GitHub, I would ask that [mine][1] be linked to, as it contains more up-to-date resources and is better-organized. Furthemore, it seems the maintainer is making no effort to keep up with my changes or even introduce new material, which is basically just sending users down a bad alleyway.

[1]: https://notabug.org/koz.ross/awesome-c

**Comment by aleksandar-todorovic** [comment]
Yes, the reason why my list is included instead of your original list is because I'm hosting it on GitHub. Since we want to make the collaboration as easy as possible, it doesn't seem fair to redirect the visitors to a new site and make it mandatory to create accounts on other services just to be able to contribute to the list.

I'm definitely not suggesting that GitHub is better than the other similar services, I'm just saying that we have decided to link the lists hosted here to make the contributing process as similar as possible across the material we're linking from here.

`awesome-c` is not the only list that got forked, removed or rejected because of this.

**Comment by Jookia** [comment]
Why not mirror the list rather than forking it, aleksandar? That way you can get the best of both worlds. The awesome-c on github has lost a lot of history too.

**Comment by sindresorhus** [comment]
> Why not mirror the list rather than forking it, aleksandar? That way you can get the best of both worlds.

He already answered that:

> Since **we want to make the collaboration as easy as possible**, it doesn't seem fair to redirect the visitors to a new site and make it mandatory to create accounts on other services just to be able to contribute to the list.

-

@aleksandar-todorovic Maybe go through https://notabug.org/koz.ross/awesome-c and add anything missing?

**Comment by aleksandar-todorovic** [comment]
@sindresorhus Everything is up to date now. Sorry it took me so long.
