### ISSUE TITLE
Helping sorting the Miscellaneous category

### ISSUE THREAD

**Issue by AllThingsSmitty** [sindresorhus/awesome#550]
As mentioned in https://github.com/sindresorhus/awesome/issues/548#issuecomment-189576619, it will be helpful if we can go through the Miscellaneous section and group resources together to form new categories. A category should have at least 2, preferably 3 items.

**Comment by davisonio** [comment]
Some suggestions for categories I have:

- Change `Content Management System` to something else (this is too specific in my opinion). Maybe we could change this to `Web Applications` or maybe `Applications`? This would include the items under content management system, FOSS Production Apps, Sketch (OS X app), Self Hosted, Slack
- 'Learn' should be removed because anything on this list could be considered for learning. Some of the items there can go under the computer science category.

Thoughts?

**Comment by sindresorhus** [comment]
I would put the CMS stuff in the Back-End Category. Would be weird to mix CMS and a desktop app like Sketch.

Learn is a valid category. It's true you can learn from each list. The learn category is for lists that link to learning material. I guess we could make that clearer.

**Comment by AllThingsSmitty** [comment]
I see a few projects under Misc. with an "Open Source/FOSS" title, maybe an `Open Source` category would be helpful.

While every project in this list is technically open source, and the `Computer Science` and `Gaming` categories each have projects listed with an "Open Source" title, maybe this could be more `Open Source - Generic`.

Thoughts?

**Comment by davisonio** [comment]
Maybe a `Work` category? for Programming Interviews, Niche Job Boards, Hacking Spots, Research Tools, Productivity, Remote Jobs.

Or a `Business` category? for Open Companies, Places to Post Your Startup, OKR Methodology.

**Comment by sindresorhus** [comment]
I'm still looking for help with this. The Misc section is growing very large.

**Comment by davisonio** [comment]
Made a start #871

**Comment by sindresorhus** [comment]
I'm still looking for help with this, but gonna close the issue as it's been stale for a long time.
