### ISSUE TITLE
Let's add description to entries

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#928]
I could use some help adding descriptions to entries in this list. The descriptions should be as succinct as possible. Short, but descriptive. They should be about the project/theme, **NOT** the list itself.

# If you decide to do a PR, please do at least 10 descriptions.

## Correct

```
- [AVA](…) - Test runner.
```

## Not correct

```
- [AVA](…) - Full featured test runner with magic, unicorns, and many other things.
```

## Not correct

```
- [AVA](…) - Resources for AVA.
```

## Not correct

```
- [AVA](…) - Awesome resources.
```

## Not correct

```
- [AVA](…) - List of testing resources.
```

**Comment by AllThingsSmitty** [comment]
I like this. I was just viewing [Awesome Hacking](https://github.com/Hack-with-Github/Awesome-Hacking) and they have a table layout with a short description next to each repo that flows nicely.

Would you be using each individual repo's description, e.g., [Awesome](https://github.com/sindresorhus/awesome): "A curated list of awesome lists", and/or edit that to meet the succinct, descriptive requirement?

I'll happily update my own entries and others as I can.

**Comment by sindresorhus** [comment]
> or edit that to meet the succinct, descriptive requirement?

This. Most of the descriptions are not very good. I want good and succinct descriptions.

**Comment by AllThingsSmitty** [comment]
Got it.

Do you want to stick with your current formatting:

- [AVA](…) - Test runner.

Or do you want to start adding items in a table:

| Project | Description | 
|---|---|
| [npm]()  | Package manager |
| [AVA]()  | Test runner |

The latter would take more time.

**Comment by sindresorhus** [comment]
Current formatting.

**Comment by WillemMali** [comment]
Hey, I've progressed a bit with my fork, would you like to discuss a data exchange program sometime?

I'd like it if we didn't have to duplicate our efforts. I've fixed a few broken links and standardized on only tracking HTTPS Git repos currently (and assuming that URL minus the `.git` is the project page) which works for all repos so far (I had to edit a few URLs because some linked to concrete files instead of project pages).

I have converted your Markdown to 372 YAML files (there goes a Sunday), validated the liveliness of all repos (I removed a single active repo with 19 pull requests and 5 months of inactivity) and normalized the links (I only store the `https://.*/.*.git` links now as they perfectly map to the the project pages) and set up a mirroring script (all repos together with complete revision history are 1.9B at the moment).

**Comment by WillemMali** [comment]
I've also noticed that there are multiple different descriptions/taggings necessary to cover all repos: some only cover 1 thing (a language, a library, a framework, a methodology, a field of study), others cover something related to a thing (talks about library X) and some just have themes (developer and designer tools).

This made my current iteration of categories a bit disjointed, as I figured this out while copy-pasting a generated list of YAML descriptions into individual YAML files while adding categories (referencing your headers in the Markdown and the project pages themselves).

**Comment by sindresorhus** [comment]
> Hey, I've progressed a bit with my fork, would you like to discuss a data exchange program sometime?

Happy to review PRs for improvements, but Awesome is never going to switch away from Markdown.

**Comment by samjbmason** [comment]
For descriptions for awesome projects in general is it possible to add slightly longer descriptions than the one liner. Is there precedent for that somewhere in another list?

Maybe something like an indented description under the point

**Comment by sindresorhus** [comment]
@samjbmason Why? Can you provide an example of what you'd like to see?

**Comment by samjbmason** [comment]
A lot of the links in my list will require a little bit more info than just the tag line. For example if I was making a list for awesome hiking routes I would probably need distance, elevation, ground type etc and I'm just not sure how that would look on the one line

________________________________

**Comment by samjbmason** [comment]
Sorry @sindresorhus was on my phone last night so couldn't send over a example. So in the example I mentioned above instead of having the below:

- [Cool Hiking Route Cotswolds](http://some-to-route.com) - Distance: 200km - Elevation: 1000m - Some other potentially important details

I was wondering if would make more sense having a way of expanding the details, at first I though maybe a indented paragraph below like so:

- [Cool Hiking Route Cotswolds](http://some-to-route.com)
   Some more info, distance: 200km, elevation: 1000m, some other important details

Bu the more I think about it I wonder if it would make sense to have a nested list for bulleted details

- [Cool Hiking Route Cotswolds](http://some-to-route.com)
   - Distance: 200km
   - Elevation: 1000m
   - Some other important details 

It would be cool to get your feedback on any issues you forsee

**Comment by sindresorhus** [comment]
@samjbmason Yes, it really depends on what information you're going to show. `- [Title](URL) - Description.` is good for most use-cases though. In your case, I would go with your last example.

**Comment by TSIIAM** [comment]
@sindresorhus  I wanted to help and added some descriptions, let me know if something is wrong, first PR.

**Comment by aditisingh2362** [comment]
@sindresorhus This is my first PR. Added descriptions for some Back-End development. Thank you for your time!

**Comment by sindresorhus** [comment]
Closing. Most important entries have descriptions now and for the rest, it's faster for me to do it myself than reviewing PRs for it.
