### ISSUE TITLE
awesome-js site, analogous to awesome-ruby.com?

### ISSUE THREAD

**Issue by jm3** [sindresorhus/awesome#975]
Hi, this is a bit off-topic, but:

has anyone made something like `awesome-javascript.com` or the like, the way that [awesome-ruby.com](http://awesome-ruby.com/) puts an easier to navigate front-end on the [awesome-ruby repo](https://github.com/markets/awesome-ruby)?

**Comment by vsemozhetbyt** [comment]
See https://github.com/ankitgyawali/awesome-interface -> https://ankitgyawali.github.io/awesome-interface/#/home -> https://ankitgyawali.github.io/awesome-interface/#/awesome/%20Programming%20Languages/JavaScript

**Comment by jm3** [comment]
@vsemozhetbyt neat. but that doesn't really do what we're talking about, i.e. give the user navigation among the different Javascript sections. This just puts the list into a smaller frameset; the left hand navigation links only to the entire Javascript list as a whole, unless I'm mistaken.

**Comment by aleksandar-todorovic** [comment]
Ah, so you're basically looking just for something that will show the table of content on the left side?

Don't know if anything like that exists (awesome-interface and [awesome-search](https://github.com/lockys/AwesomeSearch)) don't support it, and I don't think it's too big of an advantage to build one from scratch. As such, you should probably raise the issue with those two projects explaining your preferred use case for those projects.

In any case, I think that this is more suitable as an issue for awesome-ruby repo, since this issue implicates that repo directly, and, since this doesn't influence other repos (other than talking about web interfaces which we've done extensively multiple times), I'm going to close this. 

Hope that's okay with you. If not, please ping back here.
